### ISSUE TITLE
edit an auction until first bid

### ISSUE THREAD

**Issue by Lafunamor** [ese-unibe-ch/ese2012-team3#110]

**Comment by pas** [comment]
Implemented in Auction but not yet in UI

**Comment by pas** [comment]
TODO:

1) fill in post '/item/:id/auction/edit'. see post '/item/:id/edit for that

**Comment by lyriael** [comment]
in addition edit the form for the end of auction.

instead of specifing a date, make a form where the number of days ( hours, minutes) until the end of the auction can be entered.

(changes in: _create_edit_auction.erb)

**Comment by lyriael** [comment]
While working on it, I encountered the following problem:

scenario: You edit an auction, but the end_time remains the sime. This gives a error. (If you pick a new date, even if it is the same again, alll is ok)
The problem is, that the end of an auction usually is displayed like this: Thu Nov 29 16:18:00 +0100 2012 and this is also the string, that is being passed in params[:end_time].
However marketplace.rb (in controller) offers a method to parse String to time format, but unfortunately the format is dd.mm.yyyy hh:mm.
So, i cannot compare or replace the end_time.

I see three options:
- brutal force: make another string parser (it will inclune a lot of cases, and I think it's ugly)
- sneaky way: check for string lenght. if the string is longer than 16, the date hasn't been changed.
- clean&clueless: somehow find out where the time object is formated in such way and change that.

If you have an idea, plz tell me. Otherwise I'll probably end up going for the first or second option.

**Comment by lyriael** [comment]
oh.... as usual, as soon as I ask for help, I find what I'm looking for. in auction.rb (model) there is the method end_time that displays it.

Although finding it that doesn't solve my problem...

Edit: Ok, with 'date.rb' I can make a pretty simiple parse, sorry for spaming
Edit2: Sorry for being a drama-queen, it worked out very neatly. I used DateTime, where the exact methoede needed was provided :)
