### ISSUE TITLE
Admin can change localization keys' values - error checking

### ISSUE THREAD

**Issue by Masterxilo** [ese-unibe-ch/ese2012-team3#181]
Some values must contain placeholders %s or %d.%m.%Y %H:%M, namely the values of
- LOCAL_DATE_TIME_FORMAT
- PLACED_BID_AT_FOR_CREDITS

we should check for errors with these.

**Comment by MichaelKohler** [comment]
PLACED_BID_AT_FOR_CREDITS: what if in some language the admin doesn't want to show the %s?
LOCAL_DATE_TIME_FORMAT: what if the admin wants it to be only the year so he inputs %Y? That's gonna be hard to check and a check if there's a % doesn't make much sense.

I am strongly against this error checking, since the admin has the responsibility over the language translation and we shouldn't interfere with that.

**Comment by Masterxilo** [comment]
Well that's okay with the LOCAL_DATE_TIME_FORMAT, I guess we can leave that as it is, because the time formatting function doesn't make any assumptions about the format string.

But I think the sprintf used to do the PLACED_BID_AT_FOR_CREDITS-replacements assumes there to be exactly three %s in the format string (because we pass 3 args). Can you check what happens if you leave these out? Do you get an exception when looking at an auction with multiple bids then?

If not, I agree that we don't need to check this.

PS: Acutally, I don't think there should be an exception, in C you can do printf("hello World", 1,2,3); just fine, why would ruby handle it differently and care about extra args?

**Comment by MichaelKohler** [comment]
If you leave out the %s there is no error. So we don't need to do any error checking. -> Closing
